language: python

python:
 - pypy
 - pypy3
 - 2.7
 - 3.6
 - 3.5
 - 3.4

sudo: false

install:
 - pip install -r requirements.txt
 - pip install coverage

script:
 - coverage run --source=inxwords ./test_inxwords.py -v

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pep8 pyflakes
 - pep8 --statistics --count *.py
 - pyflakes *.py | tee >(wc -l)

matrix:
  fast_finish: true
